[supervisord]
nodaemon=true
user=root
logfile=/app/storage/logs/supervisord.log

[program:php-fpm]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/app/storage/logs/php-fpm.log

[program:nginx]
process_name=%(program_name)s_%(process_num)02d
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/app/storage/logs/nginx.log
